version: '3.8'

services:
  bytestash:
    image: ghcr.io/bytemark/bytestash:latest
    container_name: bytestash
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - TZ=UTC
    networks:
      - bytestash_network

networks:
  bytestash_network:
    driver: bridge 