version: '3.8'

services:
  casaos:
    image: icewhale/casaos:latest
    container_name: casaos
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/casaos:/var/lib/casaos
    environment:
      - TZ=UTC
    networks:
      - casaos_network

networks:
  casaos_network:
    driver: bridge 