version: '3.8'

services:
  # Grafana - Metrics visualization and dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: synology-grafana
    restart: unless-stopped
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=your_secure_password
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
    - ./configs/grafana:/etc/grafana/provisioning
    - grafana-data:/var/lib/grafana
    ports:
    - "3000:3000"
    networks:
    - synology-network
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.grafana.rule=Host(`grafana.synology.local`)"

  # InfluxDB - Time-series database
  influxdb:
    image: influxdb:2.7
    container_name: synology-influxdb
    restart: unless-stopped
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=admin
    - DOCKER_INFLUXDB_INIT_PASSWORD=your_secure_password
    - DOCKER_INFLUXDB_INIT_ORG=homelab
    - DOCKER_INFLUXDB_INIT_BUCKET=metrics
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your_admin_token
    volumes:
    - influxdb-data:/var/lib/influxdb2
    - ./configs/influxdb:/etc/influxdb2
    ports:
    - "8086:8086"
    networks:
    - synology-network
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.influxdb.rule=Host(`influxdb.synology.local`)"

  # Prometheus - Metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: synology-prometheus
    restart: unless-stopped
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--storage.tsdb.retention.time=200h'
    - '--web.enable-lifecycle'
    volumes:
    - ./configs/prometheus:/etc/prometheus
    - prometheus-data:/prometheus
    ports:
    - "9090:9090"
    networks:
    - synology-network
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.prometheus.rule=Host(`prometheus.synology.local`)"

  # Node Exporter - System metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: synology-node-exporter
    restart: unless-stopped
    command:
    - '--path.procfs=/host/proc'
    - '--path.rootfs=/rootfs'
    - '--path.sysfs=/host/sys'
    - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    ports:
    - "9100:9100"
    networks:
    - synology-network

volumes:
  grafana-data:
    driver: local
  influxdb-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  synology-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
