version: '3.8'

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    environment:
    - TZ=UTC
    - PUID=1000
    - PGID=1000
    - ADMINER_DEFAULT_SERVER=db
    ports:
    - "8080:8080"
    networks:
    - homelab
    user: "1000:1000"
    security_opt:
    - no-new-privileges:true
    read_only: false
    tmpfs:
    - /tmp
    - /var/tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.adminer.rule=Host(`adminer.local`)"
    - "traefik.http.services.adminer.loadbalancer.server.port=8080"

networks:
  homelab:
    external: true
