version: '3.8'

services:
  byte-stash:
    image: ghcr.io/byte-stash/byte-stash:latest
    container_name: byte-stash
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    networks:
      - homelab

networks:
  homelab:
    external: true 