version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      - TZ=UTC
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - VIRTUAL_HOST=pihole.local
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    networks:
      - homelab

networks:
  homelab:
    external: true 