version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    environment:
    - TZ=UTC
    - PUID=1000
    - PGID=1000
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./data:/prometheus
    ports:
    - "9090:9090"
    networks:
    - homelab
    user: "1000:1000"
    security_opt:
    - no-new-privileges:true
    read_only: false
    tmpfs:
    - /tmp
    - /var/tmp
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--storage.tsdb.retention.time=200h'
    - '--web.enable-lifecycle'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/-/healthy" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.prometheus.rule=Host(`prometheus.local`)"
    - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

networks:
  homelab:
    external: true
