version: "3.8"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex-media-server
    network_mode: host
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    - PLEX_CLAIM= # Add your Plex claim token here
    - VERSION=latest
    volumes:
    - ./config:/config
    - ./media/tv:/data/tvshows
    - ./media/movies:/data/movies
    - ./media/music:/data/music
    - ./media/photos:/data/photos
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.plex.rule=Host(`plex.yourdomain.com`)"
    - "traefik.http.routers.plex.entrypoints=websecure"
    - "traefik.http.routers.plex.tls.certresolver=letsencrypt"
    security_opt:
    - no-new-privileges:true
    read_only: false
    tmpfs:
    - /tmp
    - /var/lib/plexmediaserver/tmp
