version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - TZ=UTC
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - homelab

networks:
  homelab:
    external: true 