version: '3.8'

services:
  netbox:
    image: netboxcommunity/netbox:latest
    container_name: netbox
    restart: unless-stopped
    environment:
    - TZ=UTC
    - DB_NAME=netbox
    - DB_USER=netbox
    - DB_PASSWORD=${NETBOX_DB_PASSWORD}
    - DB_HOST=postgres
    - REDIS_HOST=redis
    - SECRET_KEY=${NETBOX_SECRET_KEY}
    - REDIS_PASSWORD=${NETBOX_REDIS_PASSWORD}
    - REDIS_DB=0
    - REDIS_SSL=false
    - REDIS_VERIFY_SSL=false
    volumes:
    - ./data:/opt/netbox/netbox/media
    ports:
    - "8000:8080"
    depends_on:
    - postgres
    - redis
    networks:
    - homelab
    user: "1000:1000"
    security_opt:
    - no-new-privileges:true
    read_only: false
    tmpfs:
    - /tmp
    - /var/tmp
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.netbox.rule=Host(`netbox.local`)"
    - "traefik.http.services.netbox.loadbalancer.server.port=8080"

  postgres:
    image: postgres:15-alpine
    container_name: netbox-postgres
    restart: unless-stopped
    environment:
    - POSTGRES_DB=netbox
    - POSTGRES_USER=netbox
    - POSTGRES_PASSWORD=${NETBOX_DB_PASSWORD}
    - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    networks:
    - homelab
    user: "1000:1000"
    security_opt:
    - no-new-privileges:true
    read_only: false
    tmpfs:
    - /tmp
    - /var/tmp
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U netbox -d netbox" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
    - "traefik.enable=false"

  redis:
    image: redis:7-alpine
    container_name: netbox-redis
    restart: unless-stopped
    command: redis-server --requirepass ${NETBOX_REDIS_PASSWORD}
    networks:
    - homelab
    user: "1000:1000"
    security_opt:
    - no-new-privileges:true
    read_only: false
    tmpfs:
    - /tmp
    - /var/tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
    - "traefik.enable=false"

networks:
  homelab:
    external: true
