version: '3.8'

services:
  tianji:
    image: tianji/tianji:latest
    container_name: tianji
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    networks:
      - homelab

networks:
  homelab:
    external: true 